// <auto-generated />
using AggregationApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AggregationAPI.Migrations
{
    [DbContext(typeof(AggregatedDataContext))]
    [Migration("20230906131707_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AggregationApp.AggregatedData", b =>
                {
                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("PMinusSum")
                        .HasColumnType("real");

                    b.Property<float>("PPlusSum")
                        .HasColumnType("real");

                    b.HasKey("Region");

                    b.ToTable("AData");
                });
#pragma warning restore 612, 618
        }
    }
}
